#!/bin/bash
wget https://download.java.net/java/GA/jdk16.0.2/d4a915d82b4c4fbb9bde534da945d746/7/GPL/openjdk-16.0.2_linux-aarch64_bin.tar.gz
mkdir /usr/lib/jvm
cd /usr/lib/jvm
tar xzf ~/openjdk-16.0.2_linux-aarch64_bin.tar.gz
exit
